export const types = {
    POST_EMAIL_SUBSCRIPTION_REQUEST: "POST_EMAIL_SUBSCRIPTION_REQUEST",
    POST_EMAIL_SUBSCRIPTION_SUCCESS: "POST_EMAIL_SUBSCRIPTION_SUCCESS",
    POST_EMAIL_SUBSCRIPTION_FAILURE: "POST_EMAIL_SUBSCRIPTION_FAILURE",
};
